# Generated by Django 2.2.16 on 2022-09-22 18:28

import django.db.models.deletion
import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Основной текст для публикации', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата сохраняется автоматически', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий к отзыву',
                'verbose_name_plural': 'Комментарии к отзывам',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Основной текст для публикации', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата сохраняется автоматически', verbose_name='Дата создания')),
                ('score', models.PositiveSmallIntegerField(help_text='Рейтинг, присвоенный произведению', validators=[reviews.validators.validate_score], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Отзыв к произведению',
                'verbose_name_plural': 'Отзывы к произведениям',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название произведения', max_length=256, verbose_name='Название произведения')),
                ('year', models.IntegerField(help_text='Дата издания произведения', verbose_name='Дата издания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится произведение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='reviews.Category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(help_text='Жанры, к которым относится произведение', to='reviews.Genre', verbose_name='Жанры произведения')),
            ],
            options={
                'verbose_name': 'Произведениe',
                'verbose_name_plural': 'Произведения',
                'ordering': ('id',),
            },
        ),
    ]
