# Generated by Django 2.2.16 on 2022-09-23 12:43

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220922_2128'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='title cant be from a future',
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Дата издания произведения', validators=[reviews.validators.check_year], verbose_name='Дата издания'),
        ),
    ]
